# Generated by Django 5.1.7 on 2025-04-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='insurance_document',
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='face_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
