# Generated by Django 5.1.7 on 2025-04-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='image_path',
        ),
        migrations.AddField(
            model_name='patient',
            name='face_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
    ]
