# Generated by Django 5.1.7 on 2025-03-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
