# Generated by Django 5.1.7 on 2025-03-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='emergency_type',
            field=models.CharField(blank=True, choices=[('critical', 'Critical'), ('non-critical', 'Non-Critical'), ('police', 'Police'), ('disaster', 'Disaster'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
