# Generated by Django 5.1.7 on 2025-03-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_trip_emergency_type_trip_is_emergency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='emergency_type',
            field=models.CharField(blank=True, choices=[('critical', 'Critical'), ('non-critical', 'Non-Critical')], max_length=20, null=True),
        ),
    ]
