# Generated by Django 5.1.7 on 2025-04-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_patient_insurance_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='insurance_details',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_document',
            field=models.FileField(blank=True, null=True, upload_to='insurance_documents/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='face_images/'),
        ),
    ]
