# Generated by Django 5.1.7 on 2025-03-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_driver_license_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police',
            name='badge_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='police',
            name='station_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
