# Generated by Django 5.1.7 on 2025-04-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_emergencyrequest_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttreatment',
            name='doctor_assigned',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patienttreatment',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patienttreatment',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patienttreatment',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patienttreatment',
            name='follow_up_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patienttreatment',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patienttreatment',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patienttreatment',
            name='medications_administered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patienttreatment',
            name='nurse_assigned',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patienttreatment',
            name='procedures_performed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patienttreatment',
            name='vital_signs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
