# Generated by Django 5.1.7 on 2025-04-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_patient_insurance_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='police',
            name='police_active',
            field=models.BooleanField(default=True),
        ),
    ]
