# Generated by Django 5.1.7 on 2025-03-28 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_trip_emergency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='emergency_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.emergencyrequest'),
        ),
    ]
