# Generated by Django 5.1.7 on 2025-04-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_driver_driver_active_police_police_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='car_insurance_document',
            field=models.FileField(blank=True, null=True, upload_to='car_insurance/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='car_rc_document',
            field=models.FileField(blank=True, null=True, upload_to='car_rc/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='driving_license_document',
            field=models.FileField(blank=True, null=True, upload_to='driving_licenses/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='driver_face_images/'),
        ),
    ]
