# Generated by Django 5.1.7 on 2025-03-27 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='assigned_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='base.hospital'),
        ),
    ]
